
COMPOSITE_HOME_PATH=$(PROJECT_HOME)
COMPOSITE_BIN_PATH=$(COMPOSITE_HOME_PATH)/debug
COMPOSITE_SRC_PATH=$(COMPOSITE_HOME_PATH)/src

# Compiler setting
COMPOSITE_CC=g++
COMPOSITE_CFLAG=-Wall -g

# Link setting
COMPOSITE_LPP=g++
COMPOSITE_LFLAG=

# Log setting
COMPOSITE_LOG_TYPE=-D_STLOG_
COMPOSITE_LOG_LEVEL=-DVERBOSE_LOG
COMPOSITE_LOG_SETTING=$(COMPOSITE_LOG_TYPE) $(COMPOSITE_LOG_LEVEL)


